spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        #Using File Sysytem
         native:
         # search-locations: "classpath:/config"
            search-locations: "D:/udemy_workspace/eazyBytes_work_Space_3.1.1 with docker and value annotation S6/V2-Spring_cloud_config/configserver/src/main/resources/config"
        
        #Using github
#        git:
#         uri: "https://github.com/eazybytes/eazybytes-config"
#         default-label: main
#         timeout: 5
#         clone-on-start: true
#         force-pull: true
  rabbitmq:
   host: "localhost"
   port: "5672"
   username: "guest"
   password: "guest"

management:
 endpoints:
  web:
   exposure:
     include: "*" 
        
encrypt:
  key: "45D81EC1EF61DF9Ad8D3E5BB397F9"         
server:
 port: 8071
  